# Generated by Django 4.2.20 on 2025-04-19 23:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_remove_cliente_aniversario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Classe_Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Classe', to='Clientes.classe_cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Data_Cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
