# Generated by Django 4.2.20 on 2025-04-13 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.TextField()),
                ('Sigla', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.TextField()),
                ('Referencia', models.TextField()),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categoria', to='Produtos.categoria')),
                ('Cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cor', to='Produtos.cor')),
                ('Tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tamanho', to='Produtos.tamanho')),
            ],
        ),
    ]
