# Generated by Django 4.2.20 on 2025-04-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='Descricao',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cor',
            name='Descricao',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='Descricao',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='Referencia',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='Descricao',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tamanho',
            name='Sigla',
            field=models.TextField(max_length=100),
        ),
    ]
