# Generated by Django 4.2.20 on 2025-04-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0002_alter_categoria_descricao_alter_cor_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='Valor',
        ),
    ]
