# Generated by Django 4.2.20 on 2025-04-20 00:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0003_alter_cliente_classe_cliente_and_more'),
        ('Produtos', '0002_alter_categoria_descricao_alter_cor_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_Entrega', models.DateField()),
                ('Data_Cadastro', models.DateField(default=django.utils.timezone.now)),
                ('Valor_Total', models.FloatField(default=0)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='Clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Itens_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor', models.FloatField()),
                ('Quantidade', models.FloatField()),
                ('Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Pedidos.pedidos')),
                ('Produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produto', to='Produtos.produtos')),
            ],
        ),
    ]
