# Generated by Django 4.2.20 on 2025-04-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens_pedido',
            name='Pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pedido', to='Pedidos.pedidos'),
        ),
    ]
